package com.rs.kotlin.game.world.projectile

enum class Projectile(val typeName: String) {
    STANDARD_MAGIC("standard_magic"),
    STANDARD_MAGIC_INSTANT("standard_magic_instant"),
    ARROW("arrow"),
    DRAGON_ARROW("dragon arrow"),
    BOLT("bolt"),
    DART("dart"),
    THROWING_KNIFE("throwing_knife"),
    JAVELIN("javelin"),
    CHINCHOMPA("chinchompa"),
    ELEMENTAL_SPELL("elemental_spell"),
    ANCIENT_SPELL("ancient_spell"),
    MIASMIC_SPELL("miasmic_spell"),
    BLOOD_SPELL("blood_spell"),
    ICE_SPELL("ice_spell"),
    SAP("sap"),
    LEECH("leech"),
    SOULSPLIT("soulsplit"),
    CANNON("cannon"),
    HAND_CANNON("hand_cannon"),
    SLAYER_DART("slayer_dart"),
    IBAN_BLAST("iban_blast"),
    STORM_OF_ARMADYL("storm_of_armadyl"),
    TELEPORT_BLOCK("teleport_block"),
    CRUMBLE_UNDEAD("crumble_undead"),
    SAGAIE("sagaie"),
    POLYPORE_STAFF("polypore_staff"),
    SPREAD_ALL_SLOW("spread_all"),
    CHAIN_ARROW("chain_arrow"),

    //NPCS
    DRAGONFIRE("dragonfire"),
}
