package raynna.game.player.combat.magic.dungeoneering

import raynna.game.Graphics
import raynna.game.player.combat.magic.ElementType
import raynna.game.player.combat.magic.RuneDefinitions
import raynna.game.player.combat.magic.RuneRequirement
import raynna.game.player.combat.magic.Spell
import raynna.game.player.combat.magic.SpellType
import raynna.game.player.combat.magic.Spellbook

object DungeoneeringMagicks : Spellbook(DUNGEONEERING_ID) {
    override val spells =
        listOf(
            Spell(
                id = 24,
                name = "Home teleport",
                level = 1,
                xp = 0.0,
                type = SpellType.Teleport,
                runes = emptyList(),
            ),
            Spell(
                id = 25,
                name = "Wind Strike",
                level = 1,
                xp = 5.5,
                damage = 20,
                attackSound = 220,
                hitSound = 221,
                type = SpellType.Combat,
                element = ElementType.Air,
                runes =
                    listOf(
                        RuneRequirement(RuneDefinitions.Runes.AIR, 1, true),
                        RuneRequirement(RuneDefinitions.Runes.MIND, 1),
                    ),
                animationId = 14221,
                graphicId = Graphics(457),
                projectileId = 458,
                endGraphic = Graphics(463, 100),
            ),
            Spell(
                id = 26,
                name = "Confuse",
                level = 3,
                xp = 13.0,
                attackSound = 119,
                hitSound = 121,
                type = SpellType.Combat,
                runes =
                    listOf(
                        RuneRequirement(RuneDefinitions.Runes.WATER, 3),
                        RuneRequirement(RuneDefinitions.Runes.EARTH, 2),
                        RuneRequirement(RuneDefinitions.Runes.BODY, 1),
                    ),
                animationId = 717,
                graphicId = Graphics(102, 100),
                projectileId = 103,
                endGraphic = Graphics(104, 100),
            ),
            Spell(
                id = 27,
                name = "Water Strike",
                level = 5,
                xp = 7.5,
                damage = 40,
                attackSound = 211,
                hitSound = 212,
                type = SpellType.Combat,
                element = ElementType.Water,
                runes =
                    listOf(
                        RuneRequirement(RuneDefinitions.Runes.WATER, 1),
                        RuneRequirement(RuneDefinitions.Runes.AIR, 1),
                        RuneRequirement(RuneDefinitions.Runes.MIND, 1),
                    ),
                animationId = 14220,
                graphicId = Graphics(2701),
                projectileId = 2703,
                endGraphic = Graphics(2708, 100),
            ),
            Spell(
                id = 28,
                name = "Earth Strike",
                level = 9,
                xp = 9.5,
                damage = 60,
                attackSound = 132,
                hitSound = 133,
                type = SpellType.Combat,
                element = ElementType.Earth,
                runes =
                    listOf(
                        RuneRequirement(RuneDefinitions.Runes.EARTH, 2),
                        RuneRequirement(RuneDefinitions.Runes.AIR, 1),
                        RuneRequirement(RuneDefinitions.Runes.MIND, 1),
                    ),
                animationId = 14221,
                graphicId = Graphics(2713),
                projectileId = 2718,
                endGraphic = Graphics(2723, 100),
            ),
            Spell(
                id = 29,
                name = "Weaken",
                level = 11,
                xp = 21.0,
                attackSound = 3011,
                hitSound = 3010,
                type = SpellType.Combat,
                runes =
                    listOf(
                        RuneRequirement(RuneDefinitions.Runes.WATER, 3),
                        RuneRequirement(RuneDefinitions.Runes.EARTH, 2),
                        RuneRequirement(RuneDefinitions.Runes.BODY, 1),
                    ),
                animationId = 716,
                graphicId = Graphics(105, 100),
                projectileId = 106,
                endGraphic = Graphics(107, 100),
            ),
            Spell(
                id = 30,
                name = "Fire Strike",
                level = 13,
                xp = 11.5,
                damage = 80,
                attackSound = 160,
                hitSound = 161,
                type = SpellType.Combat,
                element = ElementType.Fire,
                runes =
                    listOf(
                        RuneRequirement(RuneDefinitions.Runes.FIRE, 3),
                        RuneRequirement(RuneDefinitions.Runes.AIR, 2),
                        RuneRequirement(RuneDefinitions.Runes.MIND, 1),
                    ),
                animationId = 2791,
                graphicId = Graphics(2728),
                projectileId = 2729,
                endGraphic = Graphics(2737, 100),
            ),
            Spell(
                id = 31,
                name = "Bones to Bananas",
                level = 15,
                xp = 25.0,
                type = SpellType.Instant,
                runes =
                    listOf(
                        RuneRequirement(RuneDefinitions.Runes.EARTH, 2),
                        RuneRequirement(RuneDefinitions.Runes.WATER, 2),
                        RuneRequirement(RuneDefinitions.Runes.NATURE, 1),
                    ),
            ),
            Spell(
                id = 32,
                name = "Wind bolt",
                level = 17,
                xp = 13.5,
                damage = 90,
                attackSound = 218,
                hitSound = 219,
                type = SpellType.Combat,
                element = ElementType.Air,
                runes =
                    listOf(
                        RuneRequirement(RuneDefinitions.Runes.AIR, 2),
                        RuneRequirement(RuneDefinitions.Runes.CHAOS, 1),
                    ),
                animationId = 14221,
                graphicId = Graphics(457),
                projectileId = 459,
                endGraphic = Graphics(464, 100),
            ),
            Spell(
                id = 33,
                name = "Curse",
                level = 19,
                xp = 29.0,
                attackSound = 127,
                hitSound = 126,
                type = SpellType.Combat,
                runes =
                    listOf(
                        RuneRequirement(RuneDefinitions.Runes.WATER, 2),
                        RuneRequirement(RuneDefinitions.Runes.EARTH, 3),
                        RuneRequirement(RuneDefinitions.Runes.BODY, 1),
                    ),
                animationId = 718,
                graphicId = Graphics(108, 100),
                projectileId = 109,
                endGraphic = Graphics(110, 100),
            ),
            Spell(
                id = 34,
                name = "Bind",
                level = 20,
                xp = 30.0,
                damage = 10,
                attackSound = 101,
                hitSound = 99,
                type = SpellType.Combat,
                runes =
                    listOf(
                        RuneRequirement(RuneDefinitions.Runes.EARTH, 3),
                        RuneRequirement(RuneDefinitions.Runes.WATER, 3),
                        RuneRequirement(RuneDefinitions.Runes.NATURE, 2),
                    ),
                animationId = 710,
                graphicId = Graphics(177, 100),
                projectileId = 178,
                endGraphic = Graphics(179, 100),
                bind = 8,
            ),
            Spell(
                id = 35,
                name = "Low Alchemy",
                level = 21,
                xp = 31.0,
                type = SpellType.Item,
                runes =
                    listOf(
                        RuneRequirement(RuneDefinitions.Runes.FIRE, 3),
                        RuneRequirement(RuneDefinitions.Runes.NATURE, 1),
                    ),
            ),
            Spell(
                id = 36,
                name = "Water bolt",
                level = 23,
                xp = 16.5,
                damage = 100,
                attackSound = 209,
                hitSound = 210,
                type = SpellType.Combat,
                element = ElementType.Water,
                runes =
                    listOf(
                        RuneRequirement(RuneDefinitions.Runes.WATER, 2),
                        RuneRequirement(RuneDefinitions.Runes.AIR, 2),
                        RuneRequirement(RuneDefinitions.Runes.CHAOS, 1),
                    ),
                animationId = 14220,
                graphicId = Graphics(2701),
                projectileId = 2704,
                endGraphic = Graphics(2709, 100),
            ),
            Spell(
                id = 37,
                name = "Earth bolt",
                level = 29,
                xp = 19.5,
                damage = 110,
                attackSound = 130,
                hitSound = 131,
                type = SpellType.Combat,
                element = ElementType.Earth,
                runes =
                    listOf(
                        RuneRequirement(RuneDefinitions.Runes.EARTH, 3),
                        RuneRequirement(RuneDefinitions.Runes.AIR, 2),
                        RuneRequirement(RuneDefinitions.Runes.CHAOS, 1),
                    ),
                animationId = 14221,
                graphicId = Graphics(2714),
                projectileId = 2719,
                endGraphic = Graphics(2724, 100),
            ),
            Spell(
                id = 38,
                name = "Create Gatestone",
                level = 32,
                xp = 0.0,
                type = SpellType.Instant,
                runes =
                    listOf(
                        RuneRequirement(RuneDefinitions.Runes.COSMIC, 3),
                    ),
                animationId = 14221, // TODO CHANGE ANIMATIONS & GFX
                graphicId = Graphics(2714),
                projectileId = 2719,
                endGraphic = Graphics(2724, 100),
            ),
            Spell(
                id = 39,
                name = "Gatestone Teleport",
                level = 32,
                xp = 0.0,
                type = SpellType.Teleport,
                runes = emptyList(),
                animationId = 14221, // TODO CHANGE ANIMATIONS & GFX
                graphicId = Graphics(2714),
                projectileId = 2719,
                endGraphic = Graphics(2724, 100),
            ),
            Spell(
                id = 40,
                name = "Group Gatestone Teleport",
                level = 64,
                xp = 0.0,
                type = SpellType.Teleport,
                runes =
                    listOf(
                        RuneRequirement(RuneDefinitions.Runes.LAW, 3),
                    ),
                animationId = 14221, // TODO CHANGE ANIMATIONS & GFX
                graphicId = Graphics(2714),
                projectileId = 2719,
                endGraphic = Graphics(2724, 100),
            ),
            Spell(
                id = 41,
                name = "Fire Bolt",
                level = 35,
                xp = 22.5,
                damage = 120,
                attackSound = 157,
                hitSound = 158,
                type = SpellType.Combat,
                element = ElementType.Fire,
                runes =
                    listOf(
                        RuneRequirement(RuneDefinitions.Runes.FIRE, 4),
                        RuneRequirement(RuneDefinitions.Runes.AIR, 3),
                        RuneRequirement(RuneDefinitions.Runes.CHAOS, 1),
                    ),
                animationId = 2791,
                graphicId = Graphics(2728),
                projectileId = 2731,
                endGraphic = Graphics(2738, 100),
            ),
            Spell(
                id = 42,
                name = "Wind blast",
                level = 41,
                xp = 25.5,
                damage = 130,
                attackSound = 216,
                hitSound = 217,
                type = SpellType.Combat,
                element = ElementType.Air,
                runes =
                    listOf(
                        RuneRequirement(RuneDefinitions.Runes.AIR, 3),
                        RuneRequirement(RuneDefinitions.Runes.DEATH, 1),
                    ),
                animationId = 14221,
                graphicId = Graphics(457),
                projectileId = 460,
                endGraphic = Graphics(464, 100),
            ),
            Spell(
                id = 43,
                name = "Water blast",
                level = 47,
                xp = 28.5,
                damage = 140,
                attackSound = 207,
                hitSound = 208,
                type = SpellType.Combat,
                element = ElementType.Water,
                runes =
                    listOf(
                        RuneRequirement(RuneDefinitions.Runes.WATER, 3),
                        RuneRequirement(RuneDefinitions.Runes.AIR, 3),
                        RuneRequirement(RuneDefinitions.Runes.DEATH, 1),
                    ),
                animationId = 14220,
                graphicId = Graphics(2701),
                projectileId = 2705,
                endGraphic = Graphics(2710, 100),
            ),
            Spell(
                id = 44,
                name = "Snare",
                level = 50,
                xp = 60.0,
                damage = 20,
                attackSound = 3003,
                hitSound = 3002,
                type = SpellType.Combat,
                runes =
                    listOf(
                        RuneRequirement(RuneDefinitions.Runes.EARTH, 4),
                        RuneRequirement(RuneDefinitions.Runes.WATER, 4),
                        RuneRequirement(RuneDefinitions.Runes.NATURE, 3),
                    ),
                animationId = 710,
                graphicId = Graphics(177, 100),
                projectileId = 178,
                endGraphic = Graphics(180, 100),
                bind = 16,
            ),
            Spell(
                id = 45,
                name = "Earth Blast",
                level = 53,
                xp = 31.5,
                damage = 150,
                attackSound = 128,
                hitSound = 129,
                type = SpellType.Combat,
                element = ElementType.Earth,
                runes =
                    listOf(
                        RuneRequirement(RuneDefinitions.Runes.EARTH, 4),
                        RuneRequirement(RuneDefinitions.Runes.AIR, 3),
                        RuneRequirement(RuneDefinitions.Runes.DEATH, 1),
                    ),
                animationId = 14221,
                graphicId = Graphics(2715),
                projectileId = 2720,
                endGraphic = Graphics(2725, 100),
            ),
            Spell(
                id = 46,
                name = "High Alchemy",
                level = 55,
                xp = 65.0,
                type = SpellType.Item,
                runes =
                    listOf(
                        RuneRequirement(RuneDefinitions.Runes.FIRE, 5),
                        RuneRequirement(RuneDefinitions.Runes.NATURE, 1),
                    ),
            ),
            Spell(
                id = 47,
                name = "Fire Blast",
                level = 59,
                xp = 34.5,
                damage = 160,
                attackSound = 155,
                hitSound = 156,
                type = SpellType.Combat,
                element = ElementType.Fire,
                runes =
                    listOf(
                        RuneRequirement(RuneDefinitions.Runes.FIRE, 5),
                        RuneRequirement(RuneDefinitions.Runes.AIR, 4),
                        RuneRequirement(RuneDefinitions.Runes.DEATH, 1),
                    ),
                animationId = 2791,
                graphicId = Graphics(2728),
                projectileId = 2733,
                endGraphic = Graphics(2739, 100),
            ),
            Spell(
                id = 48,
                name = "Wind Wave",
                level = 62,
                xp = 36.0,
                damage = 170,
                attackSound = 222,
                hitSound = 223,
                type = SpellType.Combat,
                element = ElementType.Air,
                runes =
                    listOf(
                        RuneRequirement(RuneDefinitions.Runes.AIR, 5),
                        RuneRequirement(RuneDefinitions.Runes.BLOOD, 1),
                    ),
                animationId = 14221,
                graphicId = Graphics(457),
                projectileId = 461,
                endGraphic = Graphics(2699, 100),
            ),
            Spell(
                id = 49,
                name = "Water Wave",
                level = 65,
                xp = 37.5,
                damage = 180,
                attackSound = 213,
                hitSound = 214,
                type = SpellType.Combat,
                element = ElementType.Water,
                runes =
                    listOf(
                        RuneRequirement(RuneDefinitions.Runes.WATER, 7),
                        RuneRequirement(RuneDefinitions.Runes.AIR, 5),
                        RuneRequirement(RuneDefinitions.Runes.BLOOD, 1),
                    ),
                animationId = 14221,
                graphicId = Graphics(2702),
                projectileId = 2706,
                endGraphic = Graphics(2710, 100),
            ),
            Spell(
                id = 50,
                name = "Vulnerability",
                level = 66,
                xp = 76.0,
                attackSound = 3009,
                hitSound = 3008,
                type = SpellType.Combat,
                runes =
                    listOf(
                        RuneRequirement(RuneDefinitions.Runes.EARTH, 5),
                        RuneRequirement(RuneDefinitions.Runes.WATER, 5),
                        RuneRequirement(RuneDefinitions.Runes.SOUL, 1),
                    ),
                animationId = 717,
                graphicId = Graphics(167, 100),
                projectileId = 168,
                endGraphic = Graphics(169, 100),
            ),
            Spell(
                id = 51,
                name = "Monster examine",
                level = 66,
                xp = 0.0,
                type = SpellType.Target,
                runes =
                    listOf(
                        RuneRequirement(RuneDefinitions.Runes.ASTRAL, 1),
                        RuneRequirement(RuneDefinitions.Runes.COSMIC, 1),
                        RuneRequirement(RuneDefinitions.Runes.MIND, 1),
                    ),
            ),
            Spell(
                id = 52,
                name = "Cure Other",
                level = 68,
                xp = 0.0,
                type = SpellType.Target,
                runes =
                    listOf(
                        RuneRequirement(RuneDefinitions.Runes.ASTRAL, 1),
                        RuneRequirement(RuneDefinitions.Runes.LAW, 1),
                        RuneRequirement(RuneDefinitions.Runes.EARTH, 10),
                    ),
            ),
            Spell(
                id = 53,
                name = "Humidify",
                level = 68,
                xp = 0.0,
                type = SpellType.Instant,
                runes =
                    listOf(
                        RuneRequirement(RuneDefinitions.Runes.ASTRAL, 1),
                        RuneRequirement(RuneDefinitions.Runes.WATER, 3),
                        RuneRequirement(RuneDefinitions.Runes.FIRE, 1),
                    ),
            ),
            Spell(
                id = 54,
                name = "Earth Wave",
                level = 70,
                xp = 40.0,
                damage = 190,
                attackSound = 134,
                hitSound = 135,
                type = SpellType.Combat,
                element = ElementType.Earth,
                runes =
                    listOf(
                        RuneRequirement(RuneDefinitions.Runes.EARTH, 7),
                        RuneRequirement(RuneDefinitions.Runes.AIR, 5),
                        RuneRequirement(RuneDefinitions.Runes.BLOOD, 1),
                    ),
                animationId = 14221,
                graphicId = Graphics(2716),
                projectileId = 2721,
                endGraphic = Graphics(2726, 100),
            ),
            Spell(
                id = 55,
                name = "Cure Me",
                level = 70,
                xp = 0.0,
                type = SpellType.Instant,
                runes =
                    listOf(
                        RuneRequirement(RuneDefinitions.Runes.ASTRAL, 2),
                        RuneRequirement(RuneDefinitions.Runes.COSMIC, 2),
                    ),
            ),
            Spell(
                id = 56,
                name = "Enfeeble",
                level = 73,
                xp = 83.0,
                attackSound = 148,
                hitSound = 150,
                type = SpellType.Combat,
                runes =
                    listOf(
                        RuneRequirement(RuneDefinitions.Runes.EARTH, 8),
                        RuneRequirement(RuneDefinitions.Runes.WATER, 8),
                        RuneRequirement(RuneDefinitions.Runes.SOUL, 1),
                    ),
                animationId = 716,
                graphicId = Graphics(170, 100),
                projectileId = 171,
                endGraphic = Graphics(172, 100),
            ),
            Spell(
                id = 57,
                name = "Cure Group",
                level = 74,
                xp = 0.0,
                type = SpellType.Instant,
                runes =
                    listOf(
                        RuneRequirement(RuneDefinitions.Runes.ASTRAL, 2),
                        RuneRequirement(RuneDefinitions.Runes.COSMIC, 2),
                    ),
            ),
            Spell(
                id = 58,
                name = "Fire Wave",
                level = 75,
                xp = 42.5,
                damage = 200,
                attackSound = 162,
                hitSound = 163,
                type = SpellType.Combat,
                element = ElementType.Fire,
                runes =
                    listOf(
                        RuneRequirement(RuneDefinitions.Runes.FIRE, 7),
                        RuneRequirement(RuneDefinitions.Runes.AIR, 5),
                        RuneRequirement(RuneDefinitions.Runes.BLOOD, 1),
                    ),
                animationId = 2791,
                graphicId = Graphics(2728, 0),
                projectileId = 2735,
                endGraphic = Graphics(2740, 100),
            ),
            Spell(
                id = 59,
                name = "Entangle",
                level = 79,
                xp = 90.0,
                damage = 30,
                attackSound = 151,
                hitSound = 153,
                type = SpellType.Combat,
                runes =
                    listOf(
                        RuneRequirement(RuneDefinitions.Runes.EARTH, 5),
                        RuneRequirement(RuneDefinitions.Runes.WATER, 5),
                        RuneRequirement(RuneDefinitions.Runes.NATURE, 4),
                    ),
                animationId = 710,
                graphicId = Graphics(177, 100),
                projectileId = 178,
                endGraphic = Graphics(181, 100),
                bind = 24,
            ),
            Spell(
                id = 60,
                name = "Stun",
                level = 80,
                xp = 90.0,
                attackSound = 3004,
                hitSound = 3005,
                type = SpellType.Combat,
                runes =
                    listOf(
                        RuneRequirement(RuneDefinitions.Runes.EARTH, 12),
                        RuneRequirement(RuneDefinitions.Runes.WATER, 12),
                        RuneRequirement(RuneDefinitions.Runes.SOUL, 1),
                    ),
                animationId = 718,
                graphicId = Graphics(173, 100),
                projectileId = 174,
                endGraphic = Graphics(107, 100),
            ),
            Spell(
                id = 61,
                name = "Wind Surge",
                level = 81,
                xp = 44.5,
                damage = 220,
                attackSound = 7866,
                hitSound = 7867,
                type = SpellType.Combat,
                element = ElementType.Air,
                runes =
                    listOf(
                        RuneRequirement(RuneDefinitions.Runes.AIR, 7),
                        RuneRequirement(RuneDefinitions.Runes.BLOOD, 1),
                        RuneRequirement(RuneDefinitions.Runes.DEATH, 1),
                    ),
                animationId = 10546,
                graphicId = Graphics(457),
                projectileId = 462,
                endGraphic = Graphics(2700, 100),
            ),
            Spell(
                id = 62,
                name = "Water Surge",
                level = 85,
                xp = 46.5,
                damage = 240,
                attackSound = 7834,
                hitSound = 7822,
                type = SpellType.Combat,
                element = ElementType.Water,
                runes =
                    listOf(
                        RuneRequirement(RuneDefinitions.Runes.WATER, 10),
                        RuneRequirement(RuneDefinitions.Runes.AIR, 7),
                        RuneRequirement(RuneDefinitions.Runes.BLOOD, 1),
                        RuneRequirement(RuneDefinitions.Runes.DEATH, 1),
                    ),
                animationId = 10542,
                graphicId = Graphics(2701),
                projectileId = 2707,
                endGraphic = Graphics(2712, 100),
            ),
            Spell(
                id = 63,
                name = "Earth Surge",
                level = 90,
                xp = 48.5,
                damage = 260,
                attackSound = 7914,
                hitSound = 7919,
                type = SpellType.Combat,
                element = ElementType.Earth,
                runes =
                    listOf(
                        RuneRequirement(RuneDefinitions.Runes.EARTH, 10),
                        RuneRequirement(RuneDefinitions.Runes.AIR, 7),
                        RuneRequirement(RuneDefinitions.Runes.BLOOD, 1),
                        RuneRequirement(RuneDefinitions.Runes.DEATH, 1),
                    ),
                animationId = 14209,
                graphicId = Graphics(2717),
                projectileId = 2722,
                endGraphic = Graphics(2727, 100),
            ),
            Spell(
                id = 64,
                name = "Vengeance Other",
                level = 93,
                xp = 110.0,
                type = SpellType.Target,
                runes =
                    listOf(
                        RuneRequirement(RuneDefinitions.Runes.ASTRAL, 3),
                        RuneRequirement(RuneDefinitions.Runes.DEATH, 2),
                        RuneRequirement(RuneDefinitions.Runes.EARTH, 10),
                    ),
            ),
            Spell(
                id = 65,
                name = "Vengeance",
                level = 94,
                xp = 112.0,
                type = SpellType.Instant,
                runes =
                    listOf(
                        RuneRequirement(RuneDefinitions.Runes.ASTRAL, 4),
                        RuneRequirement(RuneDefinitions.Runes.DEATH, 2),
                        RuneRequirement(RuneDefinitions.Runes.EARTH, 10),
                    ),
            ),
            Spell(
                id = 66,
                name = "Vengeance Group",
                level = 94,
                xp = 114.0,
                type = SpellType.Instant,
                runes =
                    listOf(
                        RuneRequirement(RuneDefinitions.Runes.ASTRAL, 4),
                        RuneRequirement(RuneDefinitions.Runes.DEATH, 3),
                        RuneRequirement(RuneDefinitions.Runes.EARTH, 11),
                    ),
            ),
            Spell(
                id = 67,
                name = "Fire Surge",
                level = 95,
                xp = 50.5,
                damage = 280,
                attackSound = 7932,
                hitSound = 7933,
                type = SpellType.Combat,
                element = ElementType.Fire,
                runes =
                    listOf(
                        RuneRequirement(RuneDefinitions.Runes.FIRE, 10),
                        RuneRequirement(RuneDefinitions.Runes.AIR, 10),
                        RuneRequirement(RuneDefinitions.Runes.BLOOD, 1),
                        RuneRequirement(RuneDefinitions.Runes.DEATH, 1),
                    ),
                projectileIds = listOf(2736, 2735, 2736),
                animationId = 2791,
                graphicId = Graphics(2728),
                endGraphic = Graphics(2741, 100),
            ),
        )
}
